TestCVCenter : UnitTest {
	*runAll {
		[
			TestExtCollection,
			TestExtMIDIFunc,
			TestExtFont,
			TestExtOSCCommends,
			TestCVWidget,
			TestMidiConnector,
			TestOscConnector,
			TestConnectorElementView,
			TestConnectorNameField,
			TestConnectorSelect,
			TestMidiLearnButton,
			TestMidiSrcSelect,
			TestMidiChanField,
			TestMidiCtrlField,
			TestMidiModeSelect,
			TestMidiZeroNumberBox,
			TestSnapDistanceNumberBox,
			TestMidiResolutionNumberBox,
			TestSlidersPerGroupNumberBox,
			TestMidiInitButton,
			TestConnectorRemoveButton,
			TestMappings,
			TestMappingSelect,
			TestMidiConnectorsEditorView,
			TestOscSelectsComboView,
			TestCVWidgetKnob,
			TestExtOSCFunc,
		].do(_.run)
	}
}