TestCVCenter : UnitTest {
	*runAll {
		[
			TestExtCollection,
			TestExtMIDIFunc,
			TestExtFont,
			TestCVWidget,
			TestMidiConnector,
			TestOscConnector,
			TestConnectorElementView,
			TestConnectorNameField,
			TestConnectorSelect,
			TestMidiLearnButton,
			TestMidiSrcSelect,
			TestMidiChanField,
			TestMidiCtrlField,
			TestMidiModeSelect,
			TestMidiZeroNumberBox,
			TestSnapDistanceNumberBox,
			TestMidiResolutionNumberBox,
			TestSlidersPerGroupNumberBox,
			TestMidiInitButton,
			TestPlayPauseButton,
			TestOscZeroCrossingText,
			TestConnectorRemoveButton,
			TestMappings,
			TestMappingSelect,
			TestMidiConnectorsEditorView,
			TestOscConnectorsEditorView,
			TestOscSelectsComboView,
			TestCVWidgetKnob,
			TestExtMIDIFunc,
			TestExtObject,
			// Tests with asynchronous logic
			TestExtOSCFunc,
			TestExtOSCCommands
		].do(_.run)
	}
}